services:
  altivec-intelligence:
    image: ghcr.io/jeffreybergier/altivec-intelligence:latest
    stdin_open: true
    tty: true
    environment:
      - IS_SANDBOX=1
    volumes:
      - cache:/cache
      - ~/.altivec:/root
      - .:/repo/jeffreybergier.github.io
    working_dir: /repo/jeffreybergier.github.io
    entrypoint: /bin/bash
    command: -lc "altivec-chooser"

  serve:
    image: ghcr.io/jeffreybergier/altivec-intelligence:latest
    working_dir: /repo/jeffreybergier.github.io/source
    volumes:
      - cache:/cache
      - ~/.altivec:/root
      - .:/repo/jeffreybergier.github.io
    ports:
      - "0.0.0.0:8080:8080"
    entrypoint: /bin/bash
    command: -lc "bundle install && ruby ../scripts/cache_restaurant_cards.rb && bundle exec jekyll serve --host 0.0.0.0 --port 8080"

volumes:
  cache:
